export const CHANGE_ORDER = "CHANGE_ORDER";
export const CHANGE_COLUMNS = "CHANGE_COLUMNS";
export const ADD_DEAL = "ADD_DEAL";
export const DEAL_STATUS_CLOSE = "DEAL_STATUS_CLOSE";
export const DEAL_STATUS_OPEN = "DEAL_STATUS_OPEN";
export const DEAL_STATUS_ACCEPT = "DEAL_STATUS_ACCEPT";
export const CHANGE_DEAL_FIELD = "CHANGE_DEAL_FIELD";